title: SAHIL NAYAB
logo: "E:/Mudassir Bhaiya wedding/walima photo/card 02/DSC_1288.JPG"
description: IT Infra Engineer and System Admin with a 1+ years of experience.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
